name: "gin_model"
mode: "dev"
port: 8888
version: "v0.1.55"

log:
  level: "debug"
  filename: "gin_model.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "juntao"
  password: "123456"
  dbname: "myblog"
  max_open_conns: 200
  max_idle_conns: 50

redis:
  host: "127.0.0.1"
  port: 6379
  password: "123456"
  db: 0
  pool_size: 100